<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-BQK0906" name="POMTests.DelectContactrReqTC" tests="4" failures="0" timestamp="2021-07-18T00:23:41 IST" time="342.754" errors="2">
  <testcase name="deleteContactReq" time="72.115" classname="POMTests.DelectContactrReqTC"/>
  <system-out/>
  <testcase name="deleteContactReq" time="87.618" classname="POMTests.DelectContactrReqTC">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at utilitypackage.Extentreport.testStepStatus(Extentreport.java:21)
at pagesPOM.AppLauncher.ClickContactReq(AppLauncher.java:28)
at POMTests.DelectContactrReqTC.deleteContactReq(DelectContactrReqTC.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- deleteContactReq -->
  <system-out/>
  <testcase name="deleteContactReq" time="74.100" classname="POMTests.DelectContactrReqTC"/>
  <system-out/>
  <testcase name="deleteContactReq" time="108.921" classname="POMTests.DelectContactrReqTC">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at utilitypackage.Extentreport.testStepStatus(Extentreport.java:21)
at pagesPOM.ContactRequestDashBoardPage.clickDownIcon(ContactRequestDashBoardPage.java:68)
at POMTests.DelectContactrReqTC.deleteContactReq(DelectContactrReqTC.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- deleteContactReq -->
  <system-out/>
</testsuite> <!-- POMTests.DelectContactrReqTC -->
